package mui.exception;

/**
 * Thrown when the selected menu item
 * is not valid.
 * Like all other exceptions of {@code MUI},
 * it is derived from {@code MenuException}.
 * 
 * @author Kian Nejadfard
 *
 */
public class BadMenuChoiceException extends MenuException {
	
	/**
	 * Represents the selected menu item's number.
	 */
	private int choice;
	
	/**
	 * Represents the highest valid item number.
	 */
	private int max;
	
	/**
	 * Auto-generated by Eclipse.
	 */
	private static final long serialVersionUID = 538329593135303863L;
	
	/**
	 * Constructor that initializes the exception object
	 * with the selected choice to be able to generate
	 * an informative message if needed.
	 * 
	 * @param choice The selected menu item
	 * @param max The highest integer that is select-able
	 */
	public BadMenuChoiceException(int choice, int max) {
		
		this.choice = choice;
		this.max = max;
		
	}
	
	/**
	 * Returns a string that describes why the selected menu item
	 * is not acceptable.
	 * 
	 * @return A {@code String} object stating which menu item has
	 * been selected and also the highest integer number that is acceptable.
	 */
	@Override
	public String toString() {
		
		return "Menu choice " + choice + " is not valid. It must be in the range [1, " + max + "].";
		
	}

}
