package mui.exception;

/**
 * Base class for all menu exceptions.
 * 
 * @author Kian Nejadfard
 *
 */
public class MenuException extends Throwable {

	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = -4899508546265367177L;

}
